/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImageViewerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/viewer/ImageView.ts
var import_obsidian4 = require("obsidian");

// src/utils/zoom.ts
var ZoomManager = class {
  constructor(settings) {
    this.defaultScale = 1;
    this.imageWidth = 0;
    this.imageHeight = 0;
    this.containerWidth = 0;
    this.containerHeight = 0;
    this.settings = settings;
    this.state = {
      scale: 1,
      translateX: 0,
      translateY: 0
    };
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  setImageDimensions(width, height) {
    this.imageWidth = width;
    this.imageHeight = height;
  }
  setContainerDimensions(width, height) {
    this.containerWidth = width;
    this.containerHeight = height;
  }
  getState() {
    return { ...this.state };
  }
  reset() {
    this.state = {
      scale: 1,
      translateX: 0,
      translateY: 0
    };
    this.applyDefaultZoom();
  }
  applyDefaultZoom() {
    if (this.imageWidth === 0 || this.imageHeight === 0) {
      return this.state;
    }
    this.state.scale = 1;
    this.defaultScale = 1;
    this.centerImage();
    return this.state;
  }
  centerImage() {
    this.state.translateX = 0;
    this.state.translateY = 0;
  }
  zoomIn(cursorX, cursorY) {
    return this.zoom(this.settings.zoomStep, cursorX, cursorY);
  }
  zoomOut(cursorX, cursorY) {
    return this.zoom(-this.settings.zoomStep, cursorX, cursorY);
  }
  zoom(delta, cursorX, cursorY) {
    const oldScale = this.state.scale;
    const newScale = Math.max(0.1, Math.min(10, this.state.scale + delta));
    this.state.scale = newScale;
    if (cursorX !== void 0 && cursorY !== void 0 && this.containerWidth > 0 && this.containerHeight > 0) {
      const scaleRatio = newScale / oldScale;
      const centerX = this.containerWidth / 2;
      const centerY = this.containerHeight / 2;
      this.state.translateX = (cursorX - centerX) * (1 - scaleRatio) + this.state.translateX * scaleRatio;
      this.state.translateY = (cursorY - centerY) * (1 - scaleRatio) + this.state.translateY * scaleRatio;
    } else {
      this.centerImage();
    }
    return this.state;
  }
  pan(deltaX, deltaY) {
    this.state.translateX += deltaX;
    this.state.translateY += deltaY;
    return this.state;
  }
  setScale(scale) {
    this.state.scale = Math.max(0.1, Math.min(10, scale));
    return this.state;
  }
  recenter() {
    if (this.imageWidth > 0 && this.imageHeight > 0 && this.containerWidth > 0 && this.containerHeight > 0) {
      this.centerImage();
    }
  }
  isZoomed() {
    return Math.abs(this.state.scale - this.defaultScale) > 0.01;
  }
  getScalePercentage() {
    return Math.round(this.state.scale * 100);
  }
  getCSS() {
    return `transform: translate(${this.state.translateX}px, ${this.state.translateY}px) scale(${this.state.scale})`;
  }
};

// src/viewer/ImageCanvas.ts
var ImageCanvas = class {
  constructor(container, settings) {
    this.currentImage = null;
    this.rotation = 0;
    this.flipH = false;
    this.isDragging = false;
    this.dragStart = { x: 0, y: 0 };
    this.scrollMode = false;
    this.preloadCache = /* @__PURE__ */ new Map();
    this.wheelThrottleTimer = 0;
    this.resizeObserver = null;
    this.container = container;
    this.settings = settings;
    this.zoomManager = new ZoomManager(settings);
    this.boundOnMouseMove = this.onMouseMove.bind(this);
    this.boundOnMouseUp = this.onMouseUp.bind(this);
    this.imageEl = document.createElement("img");
    this.imageEl.className = "image-viewer-canvas";
    this.setupImage();
    this.container.appendChild(this.imageEl);
    this.resizeObserver = new ResizeObserver(() => {
      requestAnimationFrame(() => this.onContainerResize());
    });
    this.resizeObserver.observe(this.container);
  }
  setupImage() {
    this.imageEl.addEventListener("mousedown", this.onMouseDown.bind(this));
    document.addEventListener("mousemove", this.boundOnMouseMove);
    document.addEventListener("mouseup", this.boundOnMouseUp);
    this.container.addEventListener("wheel", this.onWheel.bind(this), { passive: false });
    this.imageEl.addEventListener("dblclick", () => this.resetZoom());
    this.imageEl.addEventListener("load", this.onImageLoad.bind(this));
    this.imageEl.addEventListener("error", () => {
      this.imageEl.setCssProps({ "opacity": "1" });
      this.imageEl.alt = "Failed to load image";
    });
  }
  updateSettings(settings) {
    this.settings = settings;
    this.zoomManager.updateSettings(settings);
  }
  loadImage(image) {
    this.currentImage = image;
    this.rotation = 0;
    this.flipH = false;
    this.imageEl.classList.add("fading");
    const url = this.preloadCache.get(image.path) || image.file.vault.getResourcePath(image.file);
    this.preloadCache.set(image.path, url);
    requestAnimationFrame(() => {
      this.imageEl.src = url;
      this.imageEl.alt = image.name;
    });
  }
  preload(images) {
    for (const img of images) {
      if (this.preloadCache.has(img.path))
        continue;
      const url = img.file.vault.getResourcePath(img.file);
      this.preloadCache.set(img.path, url);
      const preloadImg = new Image();
      preloadImg.src = url;
    }
  }
  onImageLoad() {
    this.zoomManager.setImageDimensions(this.imageEl.naturalWidth, this.imageEl.naturalHeight);
    this.scheduleLayoutUpdate();
  }
  scheduleLayoutUpdate(retries = 0) {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        const rect = this.container.getBoundingClientRect();
        if (rect.width > 0 && rect.height > 0 || retries >= 5) {
          this.updateLayoutFromContainer();
        } else {
          setTimeout(() => this.scheduleLayoutUpdate(retries + 1), 50);
        }
      });
    });
  }
  onContainerResize() {
    if (!this.currentImage || this.imageEl.naturalWidth === 0)
      return;
    const rect = this.container.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0)
      return;
    this.zoomManager.setContainerDimensions(rect.width, rect.height);
    if (!this.zoomManager.isZoomed()) {
      this.zoomManager.reset();
    } else {
      this.zoomManager.recenter();
    }
    this.applyTransform();
    if (this.onZoomChange) {
      this.onZoomChange(this.zoomManager.getScalePercentage());
    }
  }
  updateLayoutFromContainer() {
    const rect = this.container.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0)
      return;
    this.zoomManager.setContainerDimensions(rect.width, rect.height);
    this.zoomManager.reset();
    this.applyTransform();
    this.imageEl.classList.remove("fading");
    if (this.onZoomChange) {
      this.onZoomChange(this.zoomManager.getScalePercentage());
    }
  }
  onMouseDown(e) {
    if (e.button !== 0)
      return;
    e.preventDefault();
    this.isDragging = true;
    this.dragStart = { x: e.clientX, y: e.clientY };
    this.imageEl.setCssProps({ "cursor": "grabbing" });
  }
  onMouseMove(e) {
    if (!this.isDragging)
      return;
    const deltaX = e.clientX - this.dragStart.x;
    const deltaY = e.clientY - this.dragStart.y;
    this.dragStart = { x: e.clientX, y: e.clientY };
    this.zoomManager.pan(deltaX, deltaY);
    this.applyTransform();
  }
  onMouseUp() {
    this.isDragging = false;
    this.imageEl.setCssProps({ "cursor": "grab" });
  }
  onWheel(e) {
    e.preventDefault();
    if (e.ctrlKey || e.metaKey) {
      const rect = this.container.getBoundingClientRect();
      const cursorX = e.clientX - rect.left;
      const cursorY = e.clientY - rect.top;
      if (e.deltaY < 0) {
        this.zoomManager.zoomIn(cursorX, cursorY);
      } else {
        this.zoomManager.zoomOut(cursorX, cursorY);
      }
      this.applyTransform();
      if (this.onZoomChange) {
        this.onZoomChange(this.zoomManager.getScalePercentage());
      }
    } else if (this.scrollMode || this.settings.scrollBehavior === "scroll") {
      this.zoomManager.pan(0, -e.deltaY);
      this.applyTransform();
    } else if (this.settings.scrollBehavior === "navigate" && this.onNavigate) {
      const now = Date.now();
      if (now - this.wheelThrottleTimer > 200) {
        this.wheelThrottleTimer = now;
        this.onNavigate(e.deltaY > 0 ? "next" : "prev");
      }
    }
  }
  zoomIn() {
    this.zoomManager.zoomIn();
    this.applyTransform();
    if (this.onZoomChange) {
      this.onZoomChange(this.zoomManager.getScalePercentage());
    }
  }
  zoomOut() {
    this.zoomManager.zoomOut();
    this.applyTransform();
    if (this.onZoomChange) {
      this.onZoomChange(this.zoomManager.getScalePercentage());
    }
  }
  resetZoom() {
    this.zoomManager.reset();
    this.applyTransform();
    if (this.onZoomChange) {
      this.onZoomChange(this.zoomManager.getScalePercentage());
    }
  }
  setZoom(scale) {
    this.zoomManager.setScale(scale);
    this.applyTransform();
    if (this.onZoomChange) {
      this.onZoomChange(this.zoomManager.getScalePercentage());
    }
  }
  toggleScrollMode() {
    this.scrollMode = !this.scrollMode;
  }
  rotateCW() {
    this.rotation = (this.rotation + 90) % 360;
    this.applyTransform();
  }
  rotateCCW() {
    this.rotation = (this.rotation - 90 + 360) % 360;
    this.applyTransform();
  }
  flipHorizontal() {
    this.flipH = !this.flipH;
    this.applyTransform();
  }
  applyTransform() {
    const state = this.zoomManager.getState();
    const flipScale = this.flipH ? -1 : 1;
    const sx = state.scale * flipScale;
    const sy = state.scale;
    this.imageEl.style.transform = `translate(${state.translateX}px, ${state.translateY}px) scale(${sx}, ${sy}) rotate(${this.rotation}deg)`;
  }
  getZoomState() {
    return this.zoomManager.getState();
  }
  getCurrentImage() {
    return this.currentImage;
  }
  resize() {
    const rect = this.container.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0)
      return;
    this.zoomManager.setContainerDimensions(rect.width, rect.height);
    this.zoomManager.recenter();
    this.applyTransform();
  }
  isZoomed() {
    return this.zoomManager.isZoomed();
  }
  destroy() {
    var _a;
    (_a = this.resizeObserver) == null ? void 0 : _a.disconnect();
    this.resizeObserver = null;
    document.removeEventListener("mousemove", this.boundOnMouseMove);
    document.removeEventListener("mouseup", this.boundOnMouseUp);
    this.imageEl.remove();
  }
};

// src/viewer/Gallery.ts
var THUMB_GAP = 8;
var BUFFER_COUNT = 5;
var Gallery = class {
  constructor(container, settings) {
    this.images = [];
    this.selectedIndex = 0;
    this.renderedRange = { start: -1, end: -1 };
    this.thumbElements = /* @__PURE__ */ new Map();
    this.container = container;
    this.settings = settings;
    this.scrollEl = document.createElement("div");
    this.scrollEl.className = "image-viewer-gallery-scroll";
    this.trackEl = document.createElement("div");
    this.trackEl.className = "image-viewer-gallery-track";
    this.scrollEl.appendChild(this.trackEl);
    this.container.appendChild(this.scrollEl);
    this.scrollEl.addEventListener("scroll", () => this.onScroll());
  }
  updateSettings(settings) {
    this.settings = settings;
    this.updateTrackSize();
    this.renderVisible();
  }
  setImages(images) {
    this.images = images;
    this.selectedIndex = 0;
    this.thumbElements.clear();
    this.renderedRange = { start: -1, end: -1 };
    this.updateTrackSize();
    this.renderVisible();
  }
  setCurrentIndex(index) {
    if (this.selectedIndex === index)
      return;
    const prev = this.thumbElements.get(this.selectedIndex);
    if (prev)
      prev.classList.remove("selected");
    this.selectedIndex = index;
    const current = this.thumbElements.get(index);
    if (current) {
      current.classList.add("selected");
    }
    this.scrollToIndex(index);
  }
  getThumbWidth() {
    return this.settings.thumbnailSize + THUMB_GAP;
  }
  updateTrackSize() {
    const totalWidth = this.images.length * this.getThumbWidth();
    this.trackEl.style.width = `${totalWidth}px`;
  }
  onScroll() {
    this.renderVisible();
  }
  renderVisible() {
    if (this.images.length === 0)
      return;
    const thumbW = this.getThumbWidth();
    const scrollLeft = this.scrollEl.scrollLeft;
    const viewWidth = this.scrollEl.clientWidth;
    const startIdx = Math.max(0, Math.floor(scrollLeft / thumbW) - BUFFER_COUNT);
    const endIdx = Math.min(this.images.length - 1, Math.ceil((scrollLeft + viewWidth) / thumbW) + BUFFER_COUNT);
    if (startIdx === this.renderedRange.start && endIdx === this.renderedRange.end)
      return;
    for (const [idx, el] of this.thumbElements) {
      if (idx < startIdx || idx > endIdx) {
        el.remove();
        this.thumbElements.delete(idx);
      }
    }
    for (let i = startIdx; i <= endIdx; i++) {
      if (!this.thumbElements.has(i)) {
        const thumb = this.createThumbnail(this.images[i], i);
        this.trackEl.appendChild(thumb);
        this.thumbElements.set(i, thumb);
      }
    }
    this.renderedRange = { start: startIdx, end: endIdx };
  }
  createThumbnail(image, index) {
    const size = this.settings.thumbnailSize;
    const wrapper = document.createElement("div");
    wrapper.className = "image-viewer-gallery-thumb" + (index === this.selectedIndex ? " selected" : "");
    wrapper.style.left = `${index * this.getThumbWidth()}px`;
    wrapper.style.width = `${size}px`;
    wrapper.style.height = `${size}px`;
    const img = document.createElement("img");
    img.loading = "lazy";
    img.src = image.file.vault.getResourcePath(image.file);
    img.alt = image.name;
    wrapper.appendChild(img);
    wrapper.addEventListener("click", (e) => {
      e.stopPropagation();
      this.selectAndNotify(index);
    });
    return wrapper;
  }
  selectAndNotify(index) {
    const prev = this.thumbElements.get(this.selectedIndex);
    if (prev)
      prev.classList.remove("selected");
    this.selectedIndex = index;
    const current = this.thumbElements.get(index);
    if (current)
      current.classList.add("selected");
    if (this.onSelect) {
      this.onSelect(index);
    }
  }
  scrollToIndex(index) {
    const thumbW = this.getThumbWidth();
    const thumbCenter = index * thumbW + thumbW / 2;
    const viewWidth = this.scrollEl.clientWidth;
    this.scrollEl.scrollTo({
      left: thumbCenter - viewWidth / 2,
      behavior: "smooth"
    });
  }
  navigateLeft() {
    if (this.selectedIndex > 0) {
      this.selectAndNotify(this.selectedIndex - 1);
      this.scrollToIndex(this.selectedIndex);
    }
  }
  navigateRight() {
    if (this.selectedIndex < this.images.length - 1) {
      this.selectAndNotify(this.selectedIndex + 1);
      this.scrollToIndex(this.selectedIndex);
    }
  }
  getSelectedIndex() {
    return this.selectedIndex;
  }
  focus() {
    this.scrollToIndex(this.selectedIndex);
  }
  destroy() {
    this.thumbElements.clear();
    this.scrollEl.remove();
  }
};

// src/viewer/Toolbar.ts
var import_obsidian = require("obsidian");
var Toolbar = class {
  constructor(container, settings, callbacks) {
    this.isPlaying = false;
    this.container = container;
    this.settings = settings;
    this.callbacks = callbacks;
    this.counterEl = document.createElement("span");
    this.zoomEl = document.createElement("span");
    this.slideshowBtn = document.createElement("button");
    this.render();
  }
  render() {
    this.container.addClass("image-viewer-toolbar");
    this.container.empty();
    const leftSection = this.container.createDiv({ cls: "toolbar-section" });
    this.addButton(leftSection, "chevron-left", "Previous (\u2190)", this.callbacks.onPrev);
    this.addButton(leftSection, "chevron-right", "Next (\u2192)", this.callbacks.onNext);
    this.counterEl.className = "toolbar-counter";
    leftSection.appendChild(this.counterEl);
    const centerSection = this.container.createDiv({ cls: "toolbar-section" });
    this.addButton(centerSection, "minus", "Zoom Out (-)", this.callbacks.onZoomOut);
    this.zoomEl.className = "toolbar-zoom";
    centerSection.appendChild(this.zoomEl);
    this.addButton(centerSection, "plus", "Zoom In (+)", this.callbacks.onZoomIn);
    const rightSection = this.container.createDiv({ cls: "toolbar-section" });
    this.addButton(rightSection, "rotate-ccw", "Rotate CCW (S)", this.callbacks.onRotateCCW);
    this.addButton(rightSection, "rotate-cw", "Rotate CW (W)", this.callbacks.onRotateCW);
    this.addButton(rightSection, "grid", "Gallery (G)", this.callbacks.onToggleGallery);
    this.addButton(rightSection, "info", "Info (I)", this.callbacks.onToggleInfo);
    this.slideshowBtn = this.addButton(
      rightSection,
      "play",
      "Slideshow (F5)",
      this.callbacks.onToggleSlideshow
    );
    this.addButton(rightSection, "settings", "Settings (F4)", this.callbacks.onSettings);
    this.addButton(rightSection, "x", "Close (Esc)", this.callbacks.onClose);
  }
  addButton(container, icon, tooltip, callback) {
    const btn = container.createEl("button", { cls: "toolbar-btn" });
    (0, import_obsidian.setIcon)(btn, icon);
    btn.setAttribute("aria-label", tooltip);
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      callback();
    });
    return btn;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  setCounter(current, total) {
    this.counterEl.textContent = `${current} / ${total}`;
  }
  setZoom(percentage) {
    this.zoomEl.textContent = `${percentage}%`;
  }
  setSlideshowPlaying(playing) {
    this.isPlaying = playing;
    (0, import_obsidian.setIcon)(this.slideshowBtn, playing ? "pause" : "play");
  }
  setVisible(visible) {
    this.container.style.display = visible ? "flex" : "none";
  }
  destroy() {
    this.container.empty();
  }
};

// src/utils/exif.ts
var ExifParser = class {
  static async parse(file) {
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = (e) => {
        var _a;
        try {
          const dataView = new DataView((_a = e.target) == null ? void 0 : _a.result);
          const exifData = this.parseExifData(dataView);
          resolve(exifData);
        } catch (e2) {
          resolve({});
        }
      };
      reader.onerror = () => resolve({});
      reader.readAsArrayBuffer(file.slice(0, 65536));
    });
  }
  static parseExifData(dataView) {
    const result = {};
    if (dataView.getUint16(0, false) !== 65496) {
      return result;
    }
    let offset = 2;
    const length = dataView.byteLength;
    while (offset < length) {
      if (dataView.getUint16(offset, false) === 65505) {
        const exifHeader = offset + 4;
        const tiffOffset = exifHeader + 6;
        if (this.getString(dataView, exifHeader, 6) === "Exif\0\0") {
          const littleEndian = dataView.getUint16(tiffOffset, false) === 18761;
          const ifd0Offset = tiffOffset + dataView.getUint32(tiffOffset + 4, littleEndian);
          this.parseIFD(dataView, ifd0Offset, littleEndian, result);
          const exifIFDOffset = result.exifIFDOffset;
          if (exifIFDOffset) {
            this.parseExifIFD(dataView, exifIFDOffset, littleEndian, result);
            delete result.exifIFDOffset;
          }
        }
        break;
      }
      offset += 2 + dataView.getUint16(offset + 2, false);
    }
    return result;
  }
  static parseIFD(dataView, offset, littleEndian, result) {
    const count = dataView.getUint16(offset, littleEndian);
    for (let i = 0; i < count; i++) {
      const entryOffset = offset + 2 + i * 12;
      const tag = dataView.getUint16(entryOffset, littleEndian);
      const type = dataView.getUint16(entryOffset + 2, littleEndian);
      const valueOffset = entryOffset + 8;
      switch (tag) {
        case 271:
          result.make = this.getStringValue(dataView, valueOffset, type, littleEndian);
          break;
        case 272:
          result.model = this.getStringValue(dataView, valueOffset, type, littleEndian);
          break;
        case 282:
        case 283:
          break;
        case 34665:
          result.exifIFDOffset = dataView.getUint32(valueOffset, littleEndian);
          break;
      }
    }
  }
  static parseExifIFD(dataView, offset, littleEndian, result) {
    const count = dataView.getUint16(offset, littleEndian);
    for (let i = 0; i < count; i++) {
      const entryOffset = offset + 2 + i * 12;
      const tag = dataView.getUint16(entryOffset, littleEndian);
      const type = dataView.getUint16(entryOffset + 2, littleEndian);
      const valueOffset = entryOffset + 8;
      switch (tag) {
        case 33434:
          result.exposureTime = this.getRationalValue(dataView, valueOffset, littleEndian);
          break;
        case 33437: {
          const fNumber = this.getRationalNumber(dataView, valueOffset, littleEndian);
          if (fNumber)
            result.fNumber = fNumber;
          break;
        }
        case 34855:
          result.iso = dataView.getUint16(valueOffset, littleEndian);
          break;
        case 36867:
          result.dateTime = this.getStringValue(dataView, valueOffset, type, littleEndian);
          break;
        case 37386:
          result.focalLength = this.getRationalValue(dataView, valueOffset, littleEndian);
          break;
        case 40962:
          result.width = dataView.getUint16(valueOffset, littleEndian);
          break;
        case 40963:
          result.height = dataView.getUint16(valueOffset, littleEndian);
          break;
      }
    }
  }
  static getString(dataView, offset, length) {
    let str = "";
    for (let i = 0; i < length; i++) {
      const char = dataView.getUint8(offset + i);
      if (char === 0)
        break;
      str += String.fromCharCode(char);
    }
    return str;
  }
  static getStringValue(dataView, offset, type, littleEndian) {
    if (type === 2) {
      return this.getString(dataView, offset, 32);
    }
    return "";
  }
  static getRationalValue(dataView, offset, littleEndian) {
    const numerator = dataView.getUint32(offset, littleEndian);
    const denominator = dataView.getUint32(offset + 4, littleEndian);
    if (denominator === 0)
      return "0";
    if (denominator === 1)
      return `${numerator}`;
    return `${numerator}/${denominator}`;
  }
  static getRationalNumber(dataView, offset, littleEndian) {
    const numerator = dataView.getUint32(offset, littleEndian);
    const denominator = dataView.getUint32(offset + 4, littleEndian);
    if (denominator === 0)
      return null;
    return numerator / denominator;
  }
};

// src/viewer/InfoPanel.ts
var InfoPanel = class {
  constructor(wrapper, app) {
    this.visible = false;
    this.wrapper = wrapper;
    this.app = app;
    this.panelEl = wrapper.createDiv({ cls: "image-viewer-info-panel" });
    const header = this.panelEl.createDiv({ cls: "info-panel-header" });
    header.createEl("span", { text: "Image info" });
    const closeBtn = header.createEl("button", { cls: "info-panel-close" });
    closeBtn.textContent = "\xD7";
    closeBtn.addEventListener("click", () => this.toggle());
    this.contentEl = this.panelEl.createDiv({ cls: "info-panel-content" });
  }
  isVisible() {
    return this.visible;
  }
  toggle() {
    this.visible = !this.visible;
    this.panelEl.classList.toggle("visible", this.visible);
    this.wrapper.classList.toggle("visible", this.visible);
  }
  hide() {
    this.visible = false;
    this.panelEl.classList.remove("visible");
    this.wrapper.classList.remove("visible");
  }
  async update(image, dimensions) {
    this.contentEl.empty();
    if (!image)
      return;
    this.addSection("File");
    this.addRow("Name", image.name);
    this.addRow("Path", image.path);
    this.addRow("Size", this.formatSize(image.size));
    this.addRow("Created", new Date(image.ctime).toLocaleString());
    this.addRow("Modified", new Date(image.mtime).toLocaleString());
    this.renderBacklinks(image);
    if (dimensions.width > 0) {
      this.addSection("Dimensions");
      this.addRow("Resolution", `${dimensions.width} \xD7 ${dimensions.height}`);
      const mp = dimensions.width * dimensions.height / 1e6;
      this.addRow("Megapixels", mp.toFixed(2) + " MP");
    }
    try {
      const file = await this.app.vault.readBinary(image.file);
      const blob = new Blob([file], { type: `image/${image.extension}` });
      const fileObj = new File([blob], image.name);
      const exif = await ExifParser.parse(fileObj);
      this.renderExif(exif);
    } catch (e) {
    }
  }
  renderBacklinks(image) {
    const linkedFiles = [];
    const resolvedLinks = this.app.metadataCache.resolvedLinks;
    for (const [sourcePath, links] of Object.entries(resolvedLinks)) {
      if (image.path in links) {
        linkedFiles.push(sourcePath);
      }
    }
    if (linkedFiles.length > 0) {
      this.addSection("Referenced In");
      const row = this.contentEl.createDiv({ cls: "info-panel-row" });
      const linksContainer = row.createEl("div", { cls: "info-panel-value" });
      linkedFiles.forEach((path, index) => {
        if (index > 0) {
          linksContainer.createEl("br");
        }
        const link = linksContainer.createEl("a", {
          cls: "info-panel-link",
          text: this.getFileName(path)
        });
        link.href = "#";
        link.addEventListener("click", (e) => {
          e.preventDefault();
          this.openFile(path);
        });
      });
    }
  }
  getFileName(path) {
    const parts = path.split("/");
    return parts[parts.length - 1];
  }
  openFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file) {
      void this.app.workspace.openLinkText(file.path, "", true);
    }
  }
  renderExif(exif) {
    const hasData = exif.make || exif.model || exif.exposureTime || exif.fNumber || exif.iso || exif.focalLength || exif.dateTime;
    if (!hasData)
      return;
    this.addSection("EXIF");
    if (exif.make || exif.model) {
      this.addRow("Camera", `${exif.make || ""} ${exif.model || ""}`.trim());
    }
    if (exif.exposureTime)
      this.addRow("Shutter", exif.exposureTime + "s");
    if (exif.fNumber)
      this.addRow("Aperture", "f/" + exif.fNumber.toFixed(1));
    if (exif.iso)
      this.addRow("ISO", exif.iso.toString());
    if (exif.focalLength)
      this.addRow("Focal", exif.focalLength + "mm");
    if (exif.dateTime)
      this.addRow("Date", this.formatExifDate(exif.dateTime));
  }
  addSection(title) {
    this.contentEl.createEl("h4", { cls: "info-panel-section", text: title });
  }
  addRow(label, value) {
    const row = this.contentEl.createDiv({ cls: "info-panel-row" });
    row.createEl("span", { cls: "info-panel-label", text: label });
    row.createEl("span", { cls: "info-panel-value", text: value });
  }
  formatSize(bytes) {
    if (bytes < 1024)
      return bytes + " B";
    if (bytes < 1024 * 1024)
      return (bytes / 1024).toFixed(1) + " KB";
    return (bytes / (1024 * 1024)).toFixed(2) + " MB";
  }
  formatExifDate(dateStr) {
    const parts = dateStr.split(" ");
    if (parts.length === 2) {
      const d = parts[0].split(":");
      if (d.length === 3)
        return `${d[0]}-${d[1]}-${d[2]} ${parts[1]}`;
    }
    return dateStr;
  }
  destroy() {
    this.panelEl.remove();
  }
};

// src/viewer/CropModal.ts
var import_obsidian2 = require("obsidian");
var CropModal = class extends import_obsidian2.Modal {
  constructor(app, image) {
    super(app);
    this.selection = null;
    this.isSelecting = false;
    this.startPoint = { x: 0, y: 0 };
    this.shiftPressed = false;
    this.scale = 1;
    this.imageWidth = 0;
    this.imageHeight = 0;
    this.image = image;
    this.boundOnKeyDown = this.onKeyDown.bind(this);
    this.boundOnKeyUp = this.onKeyUp.bind(this);
  }
  async onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.addClass("image-viewer-crop-modal");
    modalEl.setCssProps({
      "width": "90vw",
      "height": "90vh",
      "max-width": "1200px",
      "max-height": "800px"
    });
    contentEl.createEl("h2", { text: "Crop image" });
    const canvasContainer = contentEl.createDiv({ cls: "crop-canvas-container" });
    this.canvasEl = canvasContainer.createEl("canvas");
    this.ctx = this.canvasEl.getContext("2d");
    await this.loadImage();
    this.canvasEl.addEventListener("mousedown", this.onMouseDown.bind(this));
    this.canvasEl.addEventListener("mousemove", this.onMouseMove.bind(this));
    this.canvasEl.addEventListener("mouseup", this.onMouseUp.bind(this));
    document.addEventListener("keydown", this.boundOnKeyDown);
    document.addEventListener("keyup", this.boundOnKeyUp);
    const buttonContainer = contentEl.createDiv({ cls: "crop-buttons" });
    new import_obsidian2.Setting(buttonContainer).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton((btn) => btn.setButtonText("Crop").setCta().onClick(() => this.applyCrop()));
  }
  async loadImage() {
    const url = this.image.file.vault.getResourcePath(this.image.file);
    this.imageEl = new Image();
    this.imageEl.src = url;
    await new Promise((resolve) => {
      this.imageEl.onload = () => {
        this.imageWidth = this.imageEl.naturalWidth;
        this.imageHeight = this.imageEl.naturalHeight;
        const maxWidth = this.contentEl.clientWidth - 40;
        const maxHeight = this.contentEl.clientHeight - 100;
        this.scale = Math.min(maxWidth / this.imageWidth, maxHeight / this.imageHeight, 1);
        this.canvasEl.width = this.imageWidth * this.scale;
        this.canvasEl.height = this.imageHeight * this.scale;
        this.drawImage();
        resolve();
      };
    });
  }
  drawImage() {
    this.ctx.clearRect(0, 0, this.canvasEl.width, this.canvasEl.height);
    this.ctx.drawImage(
      this.imageEl,
      0,
      0,
      this.imageWidth,
      this.imageHeight,
      0,
      0,
      this.canvasEl.width,
      this.canvasEl.height
    );
    if (this.selection) {
      this.drawSelection();
    }
  }
  drawSelection() {
    if (!this.selection)
      return;
    const { x, y, width, height } = this.selection;
    this.ctx.fillStyle = "rgba(0, 0, 0, 0.5)";
    this.ctx.fillRect(0, 0, this.canvasEl.width, this.canvasEl.height);
    this.ctx.clearRect(x, y, width, height);
    this.ctx.drawImage(
      this.imageEl,
      x / this.scale,
      y / this.scale,
      width / this.scale,
      height / this.scale,
      x,
      y,
      width,
      height
    );
    this.ctx.strokeStyle = "#fff";
    this.ctx.lineWidth = 2;
    this.ctx.setLineDash([5, 5]);
    this.ctx.strokeRect(x, y, width, height);
    this.ctx.setLineDash([]);
    this.drawHandle(x, y);
    this.drawHandle(x + width, y);
    this.drawHandle(x, y + height);
    this.drawHandle(x + width, y + height);
  }
  drawHandle(x, y) {
    this.ctx.fillStyle = "#fff";
    this.ctx.fillRect(x - 4, y - 4, 8, 8);
  }
  onMouseDown(e) {
    const rect = this.canvasEl.getBoundingClientRect();
    this.isSelecting = true;
    this.startPoint = {
      x: e.clientX - rect.left,
      y: e.clientY - rect.top
    };
    this.selection = null;
  }
  onMouseMove(e) {
    if (!this.isSelecting)
      return;
    const rect = this.canvasEl.getBoundingClientRect();
    const currentX = e.clientX - rect.left;
    const currentY = e.clientY - rect.top;
    let width = currentX - this.startPoint.x;
    let height = currentY - this.startPoint.y;
    if (this.shiftPressed) {
      const size = Math.max(Math.abs(width), Math.abs(height));
      width = width >= 0 ? size : -size;
      height = height >= 0 ? size : -size;
    }
    this.selection = {
      x: width >= 0 ? this.startPoint.x : this.startPoint.x + width,
      y: height >= 0 ? this.startPoint.y : this.startPoint.y + height,
      width: Math.abs(width),
      height: Math.abs(height)
    };
    this.drawImage();
  }
  onMouseUp() {
    this.isSelecting = false;
  }
  onKeyDown(e) {
    if (e.key === "Shift") {
      this.shiftPressed = true;
    }
  }
  onKeyUp(e) {
    if (e.key === "Shift") {
      this.shiftPressed = false;
    }
  }
  applyCrop() {
    if (!this.selection || this.selection.width === 0 || this.selection.height === 0) {
      return;
    }
    const result = {
      x: Math.round(this.selection.x / this.scale),
      y: Math.round(this.selection.y / this.scale),
      width: Math.round(this.selection.width / this.scale),
      height: Math.round(this.selection.height / this.scale)
    };
    if (this.onCrop) {
      this.onCrop(result);
    }
    this.close();
  }
  onClose() {
    document.removeEventListener("keydown", this.boundOnKeyDown);
    document.removeEventListener("keyup", this.boundOnKeyUp);
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/utils/imageLoader.ts
var import_obsidian3 = require("obsidian");
var ImageLoader = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  isImageFile(file) {
    if (!(file instanceof import_obsidian3.TFile))
      return false;
    const ext = file.extension.toLowerCase();
    return this.settings.imageExtensions.includes(ext);
  }
  loadImagesFromFolder(folderPath) {
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian3.TFolder)) {
      return [];
    }
    const images = [];
    const collectImages = (folder2) => {
      for (const child of folder2.children) {
        if (child instanceof import_obsidian3.TFile && this.isImageFile(child)) {
          images.push({
            file: child,
            path: child.path,
            name: child.name,
            extension: child.extension,
            size: child.stat.size,
            ctime: child.stat.ctime,
            mtime: child.stat.mtime
          });
        } else if (child instanceof import_obsidian3.TFolder && this.settings.scanSubfolders) {
          collectImages(child);
        }
      }
    };
    collectImages(folder);
    return this.sortImages(images);
  }
  sortImages(images) {
    const sorted = [...images];
    switch (this.settings.sortBy) {
      case "name":
        sorted.sort((a, b) => a.name.localeCompare(b.name));
        break;
      case "date":
        sorted.sort((a, b) => a.mtime - b.mtime);
        break;
      case "size":
        sorted.sort((a, b) => a.size - b.size);
        break;
      case "random":
        for (let i = sorted.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [sorted[i], sorted[j]] = [sorted[j], sorted[i]];
        }
        break;
    }
    if (!this.settings.sortAscending && this.settings.sortBy !== "random") {
      sorted.reverse();
    }
    return sorted;
  }
  getImageUrl(file) {
    return this.app.vault.getResourcePath(file);
  }
  formatFileSize(bytes) {
    if (bytes < 1024)
      return bytes + " B";
    if (bytes < 1024 * 1024)
      return (bytes / 1024).toFixed(1) + " KB";
    return (bytes / (1024 * 1024)).toFixed(2) + " MB";
  }
  getImageDimensions(file) {
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => {
        resolve({ width: img.width, height: img.height });
      };
      img.onerror = () => {
        resolve({ width: 0, height: 0 });
      };
      img.src = this.getImageUrl(file);
    });
  }
};

// src/utils/keyboard.ts
var KeyboardManager = class {
  constructor(settings) {
    this.handlers = /* @__PURE__ */ new Map();
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  register(key, handler) {
    this.handlers.set(key.toLowerCase(), handler);
  }
  unregister(key) {
    this.handlers.delete(key.toLowerCase());
  }
  handle(event) {
    const key = this.getNormalizedKey(event);
    const handler = this.handlers.get(key);
    if (handler) {
      event.preventDefault();
      event.stopPropagation();
      handler(event);
      return true;
    }
    return false;
  }
  getNormalizedKey(event) {
    const parts = [];
    if (event.ctrlKey || event.metaKey)
      parts.push("ctrl");
    if (event.shiftKey)
      parts.push("shift");
    if (event.altKey)
      parts.push("alt");
    let key = event.key.toLowerCase();
    if (key === "arrowleft")
      key = "left";
    else if (key === "arrowright")
      key = "right";
    else if (key === "arrowup")
      key = "up";
    else if (key === "arrowdown")
      key = "down";
    parts.push(key);
    return parts.join("+");
  }
};
// Standard key bindings
KeyboardManager.KEYS = {
  // Navigation
  PREV: "left",
  PREV_ALT: "a",
  NEXT: "right",
  NEXT_ALT: "d",
  FIRST: "home",
  FIRST_ALT: "ctrl+left",
  LAST: "end",
  LAST_ALT: "ctrl+right",
  PREV_FOLDER: "shift+left",
  NEXT_FOLDER: "shift+right",
  // View
  TOGGLE_GALLERY: "g",
  TOGGLE_INFO: "i",
  TOGGLE_UI: "alt+z",
  FULLSCREEN: "f11",
  FULLSCREEN_ALT: "alt+enter",
  ESCAPE: "escape",
  // Zoom
  ZOOM_IN: "+",
  ZOOM_IN_ALT: "=",
  ZOOM_OUT: "-",
  RESET_ZOOM: "r",
  TOGGLE_SCROLL_MODE: "x",
  // Edit
  ROTATE_CW: "]",
  ROTATE_CCW: "[",
  FLIP_H: "f",
  CROP: "c",
  // File
  RENAME: "f2",
  DELETE: "delete",
  DELETE_PERMANENT: "shift+delete",
  COPY: "ctrl+c",
  COPY_FILE: "ctrl+shift+c",
  PASTE: "ctrl+v",
  // Slideshow
  TOGGLE_SLIDESHOW: "f5",
  TOGGLE_LOOP: "l",
  // Other
  SETTINGS: "f4",
  HELP: "k",
  TOGGLE_BG: "b"
};

// src/viewer/ImageView.ts
var VIEW_TYPE_IMAGE_VIEWER = "image-viewer";
var ImageView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.canvas = null;
    this.gallery = null;
    this.toolbar = null;
    this.infoPanel = null;
    this.images = [];
    this.currentIndex = 0;
    this.currentFolder = "";
    this.galleryVisible = false;
    this.infoPanelVisible = false;
    this.uiVisible = true;
    this.slideshowTimer = null;
    this.isClosing = false;
    this.plugin = plugin;
    this.settings = plugin.settings;
    this.imageLoader = new ImageLoader(this.app, this.settings);
    this.keyboardManager = new KeyboardManager(this.settings);
    this.setupKeyboardHandlers();
  }
  getViewType() {
    return VIEW_TYPE_IMAGE_VIEWER;
  }
  getDisplayText() {
    const currentImage = this.images[this.currentIndex];
    return currentImage ? currentImage.name : "Image viewer";
  }
  getIcon() {
    return "image";
  }
  onOpen() {
    const { containerEl } = this;
    containerEl.addClass("image-viewer-container");
    containerEl.empty();
    containerEl.tabIndex = 0;
    this.mainContainer = containerEl.createDiv({ cls: "image-viewer-main" });
    this.imageContainer = this.mainContainer.createDiv({ cls: "image-viewer-image-container" });
    this.canvasWrapper = this.imageContainer.createDiv({ cls: "image-viewer-canvas-wrapper" });
    this.canvas = new ImageCanvas(this.canvasWrapper, this.settings);
    this.canvas.onZoomChange = (scale) => {
      var _a;
      (_a = this.toolbar) == null ? void 0 : _a.setZoom(scale);
    };
    this.canvas.onNavigate = (dir) => {
      if (dir === "prev")
        void this.prev();
      else
        void this.next();
    };
    this.createNavArrows();
    this.galleryContainer = this.canvasWrapper.createDiv({ cls: "image-viewer-gallery-strip" });
    this.gallery = new Gallery(this.galleryContainer, this.settings);
    this.gallery.onSelect = (index) => {
      void this.setIndex(index);
    };
    this.toolbarContainer = this.canvasWrapper.createDiv({ cls: "image-viewer-toolbar-container" });
    this.toolbar = new Toolbar(this.toolbarContainer, this.settings, {
      onPrev: () => {
        void this.prev();
      },
      onNext: () => {
        void this.next();
      },
      onZoomIn: () => {
        var _a;
        return (_a = this.canvas) == null ? void 0 : _a.zoomIn();
      },
      onZoomOut: () => {
        var _a;
        return (_a = this.canvas) == null ? void 0 : _a.zoomOut();
      },
      onResetZoom: () => {
        var _a;
        return (_a = this.canvas) == null ? void 0 : _a.resetZoom();
      },
      onRotateCW: () => {
        var _a;
        return (_a = this.canvas) == null ? void 0 : _a.rotateCW();
      },
      onRotateCCW: () => {
        var _a;
        return (_a = this.canvas) == null ? void 0 : _a.rotateCCW();
      },
      onToggleGallery: () => this.toggleGallery(),
      onToggleInfo: () => this.toggleInfoPanel(),
      onToggleSlideshow: () => this.toggleSlideshow(),
      onSettings: () => this.showSettings(),
      onClose: () => this.close()
    });
    this.infoBar = this.canvasWrapper.createDiv({ cls: "image-viewer-info-bar" });
    this.infoPanelContainer = this.imageContainer.createDiv({ cls: "image-viewer-info-panel-wrapper" });
    this.infoPanel = new InfoPanel(this.infoPanelContainer, this.app);
    this.registerDomEvent(containerEl, "keydown", (e) => {
      this.keyboardManager.handle(e);
    });
    this.applyTheme();
    containerEl.focus();
    return Promise.resolve();
  }
  createNavArrows() {
    const leftArrow = this.canvasWrapper.createDiv({ cls: "image-viewer-nav-arrow prev" });
    (0, import_obsidian4.setIcon)(leftArrow, "chevron-left");
    leftArrow.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.prev();
    });
    const rightArrow = this.canvasWrapper.createDiv({ cls: "image-viewer-nav-arrow next" });
    (0, import_obsidian4.setIcon)(rightArrow, "chevron-right");
    rightArrow.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.next();
    });
  }
  setupKeyboardHandlers() {
    const { KEYS } = KeyboardManager;
    this.keyboardManager.register(KEYS.PREV, () => {
      void this.prev();
    });
    this.keyboardManager.register(KEYS.PREV_ALT, () => {
      void this.prev();
    });
    this.keyboardManager.register(KEYS.NEXT, () => {
      void this.next();
    });
    this.keyboardManager.register(KEYS.NEXT_ALT, () => {
      void this.next();
    });
    this.keyboardManager.register(KEYS.FIRST, () => {
      void this.setIndex(0);
    });
    this.keyboardManager.register(KEYS.FIRST_ALT, () => {
      void this.setIndex(0);
    });
    this.keyboardManager.register(KEYS.LAST, () => {
      void this.setIndex(this.images.length - 1);
    });
    this.keyboardManager.register(KEYS.LAST_ALT, () => {
      void this.setIndex(this.images.length - 1);
    });
    this.keyboardManager.register(KEYS.TOGGLE_GALLERY, () => this.toggleGallery());
    this.keyboardManager.register(KEYS.TOGGLE_INFO, () => this.toggleInfoPanel());
    this.keyboardManager.register(KEYS.TOGGLE_UI, () => this.toggleUI());
    this.keyboardManager.register(KEYS.FULLSCREEN, () => {
      void this.toggleFullscreen();
    });
    this.keyboardManager.register(KEYS.FULLSCREEN_ALT, () => {
      void this.toggleFullscreen();
    });
    this.keyboardManager.register(KEYS.ESCAPE, () => this.handleEscape());
    this.keyboardManager.register(KEYS.ZOOM_IN, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.zoomIn();
    });
    this.keyboardManager.register(KEYS.ZOOM_IN_ALT, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.zoomIn();
    });
    this.keyboardManager.register(KEYS.ZOOM_OUT, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.zoomOut();
    });
    this.keyboardManager.register(KEYS.RESET_ZOOM, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.resetZoom();
    });
    this.keyboardManager.register(KEYS.TOGGLE_SCROLL_MODE, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.toggleScrollMode();
    });
    this.keyboardManager.register(KEYS.ROTATE_CW, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.rotateCW();
    });
    this.keyboardManager.register(KEYS.ROTATE_CCW, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.rotateCCW();
    });
    this.keyboardManager.register(KEYS.FLIP_H, () => {
      var _a;
      return (_a = this.canvas) == null ? void 0 : _a.flipHorizontal();
    });
    this.keyboardManager.register(KEYS.CROP, () => this.showCrop());
    this.keyboardManager.register(KEYS.RENAME, () => {
      void this.renameFile();
    });
    this.keyboardManager.register(KEYS.DELETE, () => {
      void this.deleteFile();
    });
    this.keyboardManager.register(KEYS.DELETE_PERMANENT, () => {
      void this.deleteFile(true);
    });
    this.keyboardManager.register(KEYS.TOGGLE_SLIDESHOW, () => this.toggleSlideshow());
    this.keyboardManager.register(KEYS.TOGGLE_LOOP, () => this.toggleLoop());
    this.keyboardManager.register(KEYS.HELP, () => this.showHelp());
    this.keyboardManager.register(KEYS.TOGGLE_BG, () => this.cycleBackground());
  }
  async loadFolder(folderPath, initialImage) {
    var _a, _b;
    this.currentFolder = folderPath;
    this.images = await this.imageLoader.loadImagesFromFolder(folderPath);
    if (this.images.length === 0) {
      new import_obsidian4.Notice("No images found in folder");
      return;
    }
    if (initialImage) {
      const index = this.images.findIndex((img) => img.path === initialImage);
      this.currentIndex = index >= 0 ? index : 0;
    } else {
      this.currentIndex = 0;
    }
    (_a = this.gallery) == null ? void 0 : _a.setImages(this.images);
    (_b = this.gallery) == null ? void 0 : _b.setCurrentIndex(this.currentIndex);
    this.loadCurrentImage();
  }
  loadCurrentImage() {
    var _a, _b;
    const image = this.images[this.currentIndex];
    if (!image)
      return;
    (_a = this.canvas) == null ? void 0 : _a.loadImage(image);
    (_b = this.toolbar) == null ? void 0 : _b.setCounter(this.currentIndex + 1, this.images.length);
    this.updateInfoBar();
    this.updateTitle();
    this.preloadAdjacentImages();
    if (this.infoPanelVisible) {
      void this.updateInfoPanel();
    }
  }
  preloadAdjacentImages() {
    var _a;
    const toPreload = [];
    if (this.currentIndex > 0)
      toPreload.push(this.images[this.currentIndex - 1]);
    if (this.currentIndex < this.images.length - 1)
      toPreload.push(this.images[this.currentIndex + 1]);
    (_a = this.canvas) == null ? void 0 : _a.preload(toPreload);
  }
  updateInfoBar() {
    const image = this.images[this.currentIndex];
    if (!image || !this.infoBar)
      return;
    const parts = [image.name];
    if (this.settings.showFilePath)
      parts.push(image.path);
    parts.push(this.imageLoader.formatFileSize(image.size));
    parts.push(new Date(image.mtime).toLocaleDateString());
    this.infoBar.textContent = parts.join(" | ");
  }
  updateTitle() {
    const image = this.images[this.currentIndex];
    if (image) {
      const leafInternal = this.leaf;
      const tabHeaderEl = leafInternal.tabHeaderInnerTitleEl;
      if (tabHeaderEl) {
        tabHeaderEl.textContent = image.name;
      }
    }
  }
  async updateInfoPanel() {
    var _a;
    const image = this.images[this.currentIndex];
    if (!image)
      return;
    const img = this.imageContainer.querySelector("img.image-viewer-canvas");
    const dimensions = {
      width: (img == null ? void 0 : img.naturalWidth) || 0,
      height: (img == null ? void 0 : img.naturalHeight) || 0
    };
    await ((_a = this.infoPanel) == null ? void 0 : _a.update(image, dimensions));
  }
  async setIndex(index) {
    var _a;
    if (index < 0) {
      index = this.settings.loopImages ? this.images.length - 1 : 0;
      if (!this.settings.loopImages)
        return;
    } else if (index >= this.images.length) {
      index = this.settings.loopImages ? 0 : this.images.length - 1;
      if (!this.settings.loopImages)
        return;
    }
    this.currentIndex = index;
    (_a = this.gallery) == null ? void 0 : _a.setCurrentIndex(index);
    this.loadCurrentImage();
  }
  async prev() {
    await this.setIndex(this.currentIndex - 1);
  }
  async next() {
    await this.setIndex(this.currentIndex + 1);
  }
  toggleGallery() {
    var _a;
    this.galleryVisible = !this.galleryVisible;
    this.galleryContainer.classList.toggle("visible", this.galleryVisible);
    if (this.galleryVisible) {
      (_a = this.gallery) == null ? void 0 : _a.focus();
    }
  }
  toggleInfoPanel() {
    var _a;
    this.infoPanelVisible = !this.infoPanelVisible;
    (_a = this.infoPanel) == null ? void 0 : _a.toggle();
    if (this.infoPanelVisible) {
      void this.updateInfoPanel();
    }
    setTimeout(() => {
      var _a2;
      return (_a2 = this.canvas) == null ? void 0 : _a2.resize();
    }, 300);
  }
  toggleUI() {
    var _a;
    this.uiVisible = !this.uiVisible;
    (_a = this.toolbar) == null ? void 0 : _a.setVisible(this.uiVisible);
    this.infoBar.style.display = this.uiVisible ? "block" : "none";
  }
  async toggleFullscreen() {
    if (document.fullscreenElement) {
      await document.exitFullscreen();
    } else {
      await this.containerEl.requestFullscreen();
    }
  }
  handleEscape() {
    var _a;
    if (document.fullscreenElement) {
      void document.exitFullscreen();
    } else if (this.infoPanelVisible) {
      this.toggleInfoPanel();
    } else if ((_a = this.canvas) == null ? void 0 : _a.isZoomed()) {
      this.canvas.resetZoom();
    } else if (this.galleryVisible) {
      this.toggleGallery();
    } else {
      this.close();
    }
  }
  showCrop() {
    const image = this.images[this.currentIndex];
    if (!image)
      return;
    const modal = new CropModal(this.app, image);
    modal.onCrop = (result) => {
      console.debug("Crop result:", result);
    };
    modal.open();
  }
  toggleSlideshow() {
    if (this.slideshowTimer) {
      this.stopSlideshow();
    } else {
      this.startSlideshow();
    }
  }
  startSlideshow() {
    var _a;
    this.slideshowTimer = setInterval(() => {
      if (this.settings.slideshowRandom) {
        const randomIndex = Math.floor(Math.random() * this.images.length);
        void this.setIndex(randomIndex);
      } else {
        if (this.currentIndex === this.images.length - 1 && !this.settings.slideshowLoop) {
          this.stopSlideshow();
          return;
        }
        void this.next();
      }
    }, this.settings.slideshowInterval * 1e3);
    (_a = this.toolbar) == null ? void 0 : _a.setSlideshowPlaying(true);
    new import_obsidian4.Notice("Slideshow started");
  }
  stopSlideshow() {
    var _a;
    if (this.slideshowTimer) {
      clearInterval(this.slideshowTimer);
      this.slideshowTimer = null;
    }
    (_a = this.toolbar) == null ? void 0 : _a.setSlideshowPlaying(false);
    new import_obsidian4.Notice("Slideshow stopped");
  }
  toggleLoop() {
    this.settings.loopImages = !this.settings.loopImages;
    void this.plugin.saveSettings();
    new import_obsidian4.Notice(`Loop: ${this.settings.loopImages ? "On" : "Off"}`);
  }
  cycleBackground() {
    const colors = ["#1a1a1a", "#2d2d2d", "#000000", "#ffffff"];
    const currentBgIndex = colors.indexOf(this.settings.backgroundColor);
    const nextIndex = (currentBgIndex + 1) % colors.length;
    this.settings.backgroundColor = colors[nextIndex];
    void this.plugin.saveSettings();
    this.applyTheme();
  }
  async renameFile() {
    var _a;
    const image = this.images[this.currentIndex];
    if (!image)
      return;
    const baseName = image.name.replace(/\.[^.]+$/, "");
    const newBaseName = await new Promise((resolve) => {
      const modal = new import_obsidian4.Modal(this.app);
      modal.titleEl.setText("Rename file");
      let inputEl;
      new import_obsidian4.Setting(modal.contentEl).setName("New name").setDesc(`Extension .${image.extension} will be kept`).addText((text) => {
        text.setValue(baseName);
        inputEl = text.inputEl;
        setTimeout(() => {
          inputEl.focus();
          inputEl.select();
        }, 50);
      });
      new import_obsidian4.Setting(modal.contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
        modal.close();
        resolve(null);
      })).addButton((btn) => btn.setButtonText("Rename").setCta().onClick(() => {
        modal.close();
        resolve(inputEl.value.trim());
      }));
      modal.open();
    });
    if (newBaseName && newBaseName !== baseName) {
      const newPath = ((_a = image.file.parent) == null ? void 0 : _a.path) + "/" + newBaseName + "." + image.extension;
      if (newPath) {
        await this.app.fileManager.renameFile(image.file, newPath);
        new import_obsidian4.Notice("File renamed");
        await this.loadFolder(this.currentFolder, newPath);
      }
    }
  }
  async deleteFile(permanent = false) {
    var _a, _b;
    const image = this.images[this.currentIndex];
    if (!image)
      return;
    const confirmed = await new Promise((resolve) => {
      const modal = new import_obsidian4.Modal(this.app);
      modal.titleEl.setText(permanent ? "Permanently delete?" : "Move to trash?");
      const msg = permanent ? `"${image.name}" will be permanently deleted. This cannot be undone.` : `"${image.name}" will be moved to trash.`;
      modal.contentEl.createEl("p", { text: msg });
      new import_obsidian4.Setting(modal.contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
        modal.close();
        resolve(false);
      })).addButton((btn) => {
        btn.setButtonText(permanent ? "Delete" : "Move to trash");
        if (permanent)
          btn.setWarning();
        else
          btn.setCta();
        btn.onClick(() => {
          modal.close();
          resolve(true);
        });
      });
      modal.open();
    });
    if (!confirmed)
      return;
    if (permanent) {
      await this.app.vault.delete(image.file);
      new import_obsidian4.Notice("File permanently deleted");
    } else {
      await this.app.fileManager.trashFile(image.file);
      new import_obsidian4.Notice("File moved to trash");
    }
    this.images.splice(this.currentIndex, 1);
    if (this.images.length === 0) {
      this.close();
      return;
    }
    if (this.currentIndex >= this.images.length) {
      this.currentIndex = this.images.length - 1;
    }
    (_a = this.gallery) == null ? void 0 : _a.setImages(this.images);
    (_b = this.gallery) == null ? void 0 : _b.setCurrentIndex(this.currentIndex);
    this.loadCurrentImage();
  }
  showSettings() {
    this.app.setting.open();
    this.app.setting.openTabById("obsidian-image-viewer");
  }
  showHelp() {
    const modal = new import_obsidian4.Modal(this.app);
    modal.titleEl.setText("Keyboard shortcuts");
    const content = modal.contentEl.createDiv({ cls: "image-viewer-help" });
    const shortcuts = [
      ["Navigation", ""],
      ["\u2190 / A", "Previous image"],
      ["\u2192 / D", "Next image"],
      ["Home", "First image"],
      ["End", "Last image"],
      ["", ""],
      ["View", ""],
      ["G", "Toggle gallery"],
      ["I", "Toggle info panel"],
      ["Alt+Z", "Toggle UI"],
      ["F11", "Fullscreen"],
      ["Esc", "Close / dismiss panels"],
      ["", ""],
      ["Zoom", ""],
      ["+", "Zoom in"],
      ["-", "Zoom out"],
      ["R", "Reset zoom"],
      ["", ""],
      ["Edit", ""],
      ["]", "Rotate clockwise"],
      ["[", "Rotate counter-clockwise"],
      ["F", "Flip horizontal"],
      ["C", "Crop"],
      ["", ""],
      ["File", ""],
      ["F2", "Rename"],
      ["Del", "Move to trash"],
      ["Shift+Del", "Delete permanently"],
      ["", ""],
      ["Slideshow", ""],
      ["F5", "Toggle slideshow"],
      ["L", "Toggle loop"]
    ];
    const table = content.createEl("table");
    shortcuts.forEach(([key, desc]) => {
      const row = table.createEl("tr");
      if (desc === "") {
        row.createEl("th", { text: key, attr: { colspan: "2" } });
      } else {
        row.createEl("td", { text: key });
        row.createEl("td", { text: desc });
      }
    });
    modal.open();
  }
  applyTheme() {
    this.containerEl.style.backgroundColor = this.settings.backgroundColor;
  }
  updateSettings(settings) {
    var _a, _b, _c;
    this.settings = settings;
    this.imageLoader.updateSettings(settings);
    this.keyboardManager.updateSettings(settings);
    (_a = this.canvas) == null ? void 0 : _a.updateSettings(settings);
    (_b = this.gallery) == null ? void 0 : _b.updateSettings(settings);
    (_c = this.toolbar) == null ? void 0 : _c.updateSettings(settings);
    this.applyTheme();
  }
  close() {
    if (this.isClosing)
      return;
    this.isClosing = true;
    this.stopSlideshow();
    this.leaf.detach();
  }
  onClose() {
    var _a, _b, _c, _d;
    this.stopSlideshow();
    (_a = this.canvas) == null ? void 0 : _a.destroy();
    (_b = this.gallery) == null ? void 0 : _b.destroy();
    (_c = this.toolbar) == null ? void 0 : _c.destroy();
    (_d = this.infoPanel) == null ? void 0 : _d.destroy();
    return Promise.resolve();
  }
};

// src/settings.ts
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  theme: "dark",
  backgroundColor: "#1a1a1a",
  showToolbar: true,
  showImageInfo: false,
  showFilePath: true,
  thumbnailSize: 120,
  galleryColumns: 6,
  scrollBehavior: "navigate",
  loopImages: true,
  sortBy: "name",
  sortAscending: true,
  slideshowInterval: 3,
  slideshowLoop: true,
  slideshowRandom: false,
  zoomStep: 0.25,
  defaultZoomMode: "fit",
  defaultFolder: "assets",
  scanSubfolders: false,
  imageExtensions: [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "bmp",
    "tiff",
    "ico",
    "svg",
    "avif",
    "heic",
    "heif",
    "psd",
    "raw",
    "cr2",
    "nef"
  ]
};

// src/settings.ts
var ImageViewerSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian5.Setting(containerEl).setName("General").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Display").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Theme").setDesc("Color theme for the viewer").addDropdown((dropdown) => dropdown.addOption("dark", "Dark").addOption("light", "Light").addOption("system", "System").setValue(this.plugin.settings.theme).onChange(async (value) => {
      this.plugin.settings.theme = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Background color").setDesc("Custom background color (hex)").addText((text) => text.setValue(this.plugin.settings.backgroundColor).onChange(async (value) => {
      this.plugin.settings.backgroundColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Show toolbar").setDesc("Display the toolbar by default").addToggle((toggle) => toggle.setValue(this.plugin.settings.showToolbar).onChange(async (value) => {
      this.plugin.settings.showToolbar = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Show file path").setDesc("Display file path in the viewer").addToggle((toggle) => toggle.setValue(this.plugin.settings.showFilePath).onChange(async (value) => {
      this.plugin.settings.showFilePath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Gallery").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Thumbnail size").setDesc("Size of thumbnails in pixels").addSlider((slider) => slider.setLimits(60, 200, 10).setValue(this.plugin.settings.thumbnailSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.thumbnailSize = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Gallery columns").setDesc("Number of columns in gallery view").addSlider((slider) => slider.setLimits(3, 12, 1).setValue(this.plugin.settings.galleryColumns).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.galleryColumns = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Navigation").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Scroll behavior").setDesc("Mouse wheel behavior").addDropdown((dropdown) => dropdown.addOption("navigate", "Navigate between images").addOption("scroll", "Scroll zoomed image").setValue(this.plugin.settings.scrollBehavior).onChange(async (value) => {
      this.plugin.settings.scrollBehavior = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Loop images").setDesc("Loop back to first image after last").addToggle((toggle) => toggle.setValue(this.plugin.settings.loopImages).onChange(async (value) => {
      this.plugin.settings.loopImages = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Sort by").setDesc("Sort images by").addDropdown((dropdown) => dropdown.addOption("name", "Name").addOption("date", "Date").addOption("size", "Size").addOption("random", "Random").setValue(this.plugin.settings.sortBy).onChange(async (value) => {
      this.plugin.settings.sortBy = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Sort ascending").setDesc("Sort in ascending order").addToggle((toggle) => toggle.setValue(this.plugin.settings.sortAscending).onChange(async (value) => {
      this.plugin.settings.sortAscending = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Slideshow").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Slideshow interval").setDesc("Time between slides (seconds)").addSlider((slider) => slider.setLimits(1, 30, 1).setValue(this.plugin.settings.slideshowInterval).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.slideshowInterval = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Loop slideshow").setDesc("Loop slideshow playback").addToggle((toggle) => toggle.setValue(this.plugin.settings.slideshowLoop).onChange(async (value) => {
      this.plugin.settings.slideshowLoop = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Random order").setDesc("Play slideshow in random order").addToggle((toggle) => toggle.setValue(this.plugin.settings.slideshowRandom).onChange(async (value) => {
      this.plugin.settings.slideshowRandom = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Zoom").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Zoom step").setDesc("Zoom increment step").addSlider((slider) => slider.setLimits(0.1, 0.5, 0.05).setValue(this.plugin.settings.zoomStep).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.zoomStep = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Default zoom mode").setDesc("How images fit initially").addDropdown((dropdown) => dropdown.addOption("fit", "Fit to window").addOption("fill", "Fill window").addOption("actual", "Actual size").setValue(this.plugin.settings.defaultZoomMode).onChange(async (value) => {
      this.plugin.settings.defaultZoomMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Folders").setHeading();
    new import_obsidian5.Setting(containerEl).setName("Default folder").setDesc("Default folder to open").addText((text) => text.setPlaceholder("assets").setValue(this.plugin.settings.defaultFolder).onChange(async (value) => {
      this.plugin.settings.defaultFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Scan subfolders").setDesc("Include images from subfolders").addToggle((toggle) => toggle.setValue(this.plugin.settings.scanSubfolders).onChange(async (value) => {
      this.plugin.settings.scanSubfolders = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian5.Setting(containerEl).setName("Reset to defaults").setDesc("Reset all settings to default values").addButton((button) => button.setButtonText("Reset").setWarning().onClick(async () => {
      this.plugin.settings = { ...DEFAULT_SETTINGS };
      await this.plugin.saveSettings();
      this.display();
    }));
    const donateSection = containerEl.createDiv({ cls: "plugin-donate-section" });
    new import_obsidian5.Setting(donateSection).setName("Support the developer").setHeading();
    donateSection.createEl("p", { text: "\u5982\u679C\u8FD9\u4E2A\u63D2\u4EF6\u5E2E\u52A9\u4E86\u4F60\uFF0C\u6B22\u8FCE\u8BF7\u4F5C\u8005\u559D\u676F\u5496\u5561", cls: "plugin-donate-desc" });
    const imgWrap = donateSection.createDiv({ cls: "plugin-donate-qr" });
    imgWrap.createEl("img", { attr: { src: this.plugin.app.vault.adapter.getResourcePath(`${this.plugin.manifest.dir}/assets/wechat-donate.jpg`), alt: "\u5FAE\u4FE1\u6253\u8D4F", width: "160" } });
    imgWrap.createEl("p", { text: "\u5FAE\u4FE1\u626B\u7801", cls: "plugin-donate-label" });
  }
};

// main.ts
var ImageViewerPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_IMAGE_VIEWER, (leaf) => {
      return new ImageView(leaf, this);
    });
    this.addRibbonIcon("image", "Open image viewer", () => {
      void this.openImageViewer(this.settings.defaultFolder);
    });
    this.addCommand({
      id: "open",
      name: "Open",
      callback: () => {
        void this.openImageViewer(this.settings.defaultFolder);
      }
    });
    this.addCommand({
      id: "open-folder",
      name: "Open folder...",
      callback: () => {
        void this.showFolderPicker();
      }
    });
    this.addCommand({
      id: "open-current-folder",
      name: "Browse current folder",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.parent) {
          if (!checking) {
            void this.openImageViewer(file.parent.path);
          }
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian6.TFolder) {
          menu.addItem((item) => {
            item.setTitle("Open in image viewer").setIcon("image").onClick(() => {
              void this.openImageViewer(file.path);
            });
          });
        } else if (file instanceof import_obsidian6.TFile && this.isImageFile(file) && file.parent) {
          menu.addItem((item) => {
            item.setTitle("Open in image viewer").setIcon("image").onClick(() => {
              void this.openImageViewer(file.parent.path, file.path);
            });
          });
        }
      })
    );
    this.addSettingTab(new ImageViewerSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_IMAGE_VIEWER)) {
      if (leaf.view instanceof ImageView) {
        leaf.view.updateSettings(this.settings);
      }
    }
  }
  isImageFile(file) {
    const ext = file.extension.toLowerCase();
    return this.settings.imageExtensions.includes(ext);
  }
  async openImageViewer(folderPath, initialImage) {
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder || !(folder instanceof import_obsidian6.TFolder)) {
      new import_obsidian6.Notice(`Folder not found: ${folderPath}`);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: VIEW_TYPE_IMAGE_VIEWER,
      active: true
    });
    const view = leaf.view;
    if (view instanceof ImageView) {
      await view.loadFolder(folderPath, initialImage);
    }
  }
  showFolderPicker() {
    const folders = this.getAllFolders(this.app.vault.getRoot());
    const modal = new FolderSuggestModal(this.app, folders, (folder) => {
      void this.openImageViewer(folder.path);
    });
    modal.open();
  }
  getAllFolders(folder) {
    const folders = [folder];
    for (const child of folder.children) {
      if (child instanceof import_obsidian6.TFolder) {
        folders.push(...this.getAllFolders(child));
      }
    }
    return folders;
  }
  onunload() {
  }
};
var FolderSuggestModal = class extends import_obsidian6.FuzzySuggestModal {
  constructor(app, folders, onChoose) {
    super(app);
    this.folders = folders;
    this.onChoose = onChoose;
  }
  getItems() {
    return this.folders;
  }
  getItemText(folder) {
    return folder.path;
  }
  onChooseItem(folder, evt) {
    this.onChoose(folder);
  }
};
